"""Exact model identity: complete-file hashing and canonical digests."""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from plag_in.errors import ConfigurationError, PathContainmentError

_CHUNK_SIZE = 1024 * 1024

# Scope label bound into every runtime source digest so the value can never
# be read as a whole-repository or release-archive digest. It covers only
# the runtime Python source that actually executes an inference request,
# and deliberately excludes tests, reports, configuration, receipts, model
# bytes and generated caches (none of which live under this package tree).
RUNTIME_SOURCE_SCOPE = "runtime_python_source:src/plag_in/**/*.py"


def hash_file(path: Path) -> str:
    """SHA-256 over the complete file contents, streamed."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(_CHUNK_SIZE)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def canonical_digest(record: dict) -> str:
    """Deterministic digest of a JSON-serialisable record, key order independent."""
    payload = json.dumps(record, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


@dataclass(frozen=True)
class ModelIdentity:
    path: str
    sha256: str
    size_bytes: int

    @classmethod
    def from_file(cls, path: Path) -> "ModelIdentity":
        resolved = path.resolve()
        return cls(
            path=str(resolved),
            sha256=hash_file(resolved),
            size_bytes=resolved.stat().st_size,
        )

    def as_dict(self) -> dict:
        return {"path": self.path, "sha256": self.sha256, "size_bytes": self.size_bytes}


def _tree_digest_from_manifest(manifest: list[dict]) -> str:
    """Canonical digest over a list of {path, sha256} entries.

    The manifest is sorted by relative path before hashing, so the on-disk
    walk order cannot change the result. Each entry binds the relative path
    to its content hash, so two runtime files with identical bytes at
    different paths produce distinct manifest entries and cannot collide.
    """
    ordered = sorted(manifest, key=lambda item: item["path"])
    return canonical_digest({"scope": RUNTIME_SOURCE_SCOPE, "files": ordered})


def compute_source_tree_digest(root: Path) -> dict:
    """Deterministic identity of every `*.py` file under `root`.

    Returns the scope label, the canonical digest and the file count.
    `__pycache__` directories are skipped so a generated bytecode cache can
    never change the digest of the source it was built from.

    Containment is enforced (CPO-04): a symlinked source entry is rejected
    outright, and a regular file whose resolved path escapes the resolved
    root is rejected the same way, so bytes living outside the package tree
    can never be attributed to it. An empty tree is rejected (CPO-03) rather
    than yielding a digest over no files.
    """
    resolved_root = Path(root).resolve()
    manifest: list[dict] = []
    for path in sorted(resolved_root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        if path.is_symlink():
            raise PathContainmentError(
                "refusing to hash a symlinked runtime source file",
                requested_path=str(path),
            )
        if not path.is_file():
            continue
        resolved_file = path.resolve()
        try:
            relative = resolved_file.relative_to(resolved_root)
        except ValueError as exc:
            raise PathContainmentError(
                "runtime source file resolves outside the package root",
                requested_path=str(resolved_file),
            ) from exc
        manifest.append({"path": relative.as_posix(), "sha256": hash_file(resolved_file)})
    if not manifest:
        raise ConfigurationError(
            "runtime source tree is empty; refusing to bind an empty source identity",
            root=str(resolved_root),
        )
    return {
        "scope": RUNTIME_SOURCE_SCOPE,
        "digest": _tree_digest_from_manifest(manifest),
        "file_count": len(manifest),
    }


def runtime_source_identity() -> dict:
    """Fresh identity of the runtime Python source that serves inference requests.

    Computed over the installed `plag_in` package tree (this module's own
    directory) on every call. There is deliberately no process-lifetime
    cache (CPO-03): the caller (`GatewayContext`) takes one snapshot at
    initialisation and recomputes this before status and before persisting a
    receipt so that any source drift under the live process is detected and
    fails closed rather than being masked by a stale cached value.
    """
    return compute_source_tree_digest(Path(__file__).resolve().parent)
